"""Build docs/agents/CONTEXT_PACK.md (DOCS-LIVE-2): the ONLY doc synced to Claude project knowledge.

    python scripts/docs/build_context_pack.py [--check] [--facts status/facts.json]

Inputs (offline, deterministic; no git, no clock):
  facts      status/facts.json from scripts/docs/collect_facts.py (objective, strategies,
             schedule, inputs_sha256). Missing or unreadable facts fail closed: no pack.
  decisions  and invariants presence are captured in facts.pack_context by the collector;
             the pack reads no source documents outside facts.json. Missing registered
             decision tables are reported as UNKNOWN, never as zero.
The header carries facts.json's inputs_sha256 -- never a git SHA -- so identical inputs give
a byte-identical pack. The output is capped at 150 lines; the build fails rather than
truncating facts. --check exits 1 when the committed file differs from a fresh build.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from typing import List, Optional, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from doc_classes import default_frontmatter  # noqa: E402
from frontmatter import render  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join("docs", "agents", "CONTEXT_PACK.md")
FACTS = os.path.join("status", "facts.json")
REGISTERED_DECISION_SOURCES = ("docs/governance/OWNER_DECISION_REGISTER.md",)
PENDING = "PENDING_OWNER"
MAX_LINES = 150


def load_facts(path: str) -> dict:
    try:
        with open(path, encoding="utf-8") as f:
            facts = json.load(f)
    except (OSError, ValueError) as exc:
        raise SystemExit(f"FACTS_UNAVAILABLE: {path}: {exc} -- run scripts/docs/collect_facts.py") from exc
    for key in ("inputs_sha256", "objective", "strategies", "schedule", "telegram_scope", "pack_context"):
        if key not in facts:
            raise SystemExit(f"FACTS_INCOMPLETE: {path} has no {key!r}")
    return facts


def open_decisions(root: str = ROOT) -> Tuple[Optional[int], List[str]]:
    """(count of PENDING_OWNER rows, sources read). Count None when no registered table exists."""
    count, sources = 0, []
    for rel in REGISTERED_DECISION_SOURCES:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            continue
        sources.append(rel)
        with open(path, encoding="utf-8") as f:
            for line in f:
                cells = [c.strip() for c in line.strip().strip("|").split("|")]
                if line.lstrip().startswith("|") and PENDING in cells:
                    count += 1
    return (count if sources else None), sources


def _b(v) -> str:
    return "—" if v is None else (f"`{str(v).lower()}`" if isinstance(v, bool) else f"`{v}`")


def _value(field) -> object:
    return field.get("value") if isinstance(field, dict) else field


def build(facts: dict, root: str = ROOT) -> str:
    context = facts["pack_context"]
    count, sources = context["pending_decisions"], context["decision_sources"]
    decisions = (f"Open decisions in registered tables: {count} (sources: "
                 + ", ".join(f"`{s}`" for s in sources) + ")." if sources
                 else "Open decisions in registered tables: UNKNOWN (no registered decision table found).")
    schedule = facts["schedule"]
    telegram_scope = facts["telegram_scope"]
    lines = [render(default_frontmatter("status")).rstrip("\n"),
             "# AG Profit Trading — Context Pack",
             "",
             "Generated by `scripts/docs/build_context_pack.py` from `status/facts.json`; do not edit by hand.",
             "This is the only document synced to Claude project knowledge. Authority stays with the sources.",
             f"inputs_sha256: `{facts['inputs_sha256']}`.",
             "",
             f"## Objective (verbatim from `{facts['objective'].get('source', 'docs/PROJECT_OBJECTIVE.md')}`)",
             "",
             facts["objective"]["text"],
             "",
             "## Invariants",
             "",
             "- Agent rules and authority order: `AGENTS.md`; non-collapsible states:",
             "  `docs/DOCUMENTATION_GOVERNANCE.md`; " + (
                 "also `docs/agents/INVARIANTS.md` (which document is authoritative is open: REG-INVARIANTS)."
                 if context["invariants_present"]
                 else "`docs/agents/INVARIANTS.md` does not exist."),
             "- Strategy authorization is owned by `strategies/registry.yaml`; this pack only mirrors it.",
             "",
             "## Authority",
             "",
             "| Strategy | version | demo_authorized | logic_verified | edge_verified |",
             "|---|---|---|---|---|"]
    lines += [f"| `{s['id']}` | {_b(s.get('version'))} | {_b(_value(s.get('demo_authorized')))} | "
              f"{_b(_value(s.get('logic_verified')))} | {_b(_value(s.get('edge_verified')))} |"
              for s in facts["strategies"]]
    lines += ["", "## Open owner decisions", "", decisions,
              "", f"## Schedule (`{schedule.get('scheduler')}`, {schedule.get('timezone')})", "",
              "| Task | cadence | start | end |", "|---|---|---|---|"]
    lines += [f"| `{t.get('name')}` | {t.get('cadence')} | {t.get('start')} | {t.get('end') or '—'} |"
              for t in schedule.get("tasks", [])]
    lines += ["", "## Telegram immediate-send scope", "",
              "Tracked policy ceiling (host-local overrides may narrow only): "
              + ", ".join(f"`{scope}`" for scope in telegram_scope.get("immediate_send_enabled", [])) + ".",
              "Disabled informational scope:"]
    lines += [f"- `{scope}`: {reason}" for scope, reason in
              sorted(telegram_scope.get("informational_disabled", {}).items())]
    out = "\n".join(lines) + "\n"
    n = out.count("\n")
    if n > MAX_LINES:
        raise ValueError(f"context pack is {n} lines (> {MAX_LINES}); shorten a section rather than truncate facts")
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--facts", default=os.path.join(ROOT, FACTS))
    args = ap.parse_args(argv)
    content, path = build(load_facts(args.facts)), os.path.join(ROOT, OUT)
    if args.check:
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        print("CONTEXT_PACK", "UP_TO_DATE" if current == content else "STALE")
        return 0 if current == content else 1
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    print(f"{OUT} {content.count(chr(10))} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
