"""multi-timeframe-market-context runtime: WRAPPER_ONLY orchestration over
market_structure/liquidity/supply_demand/entry_confirmation. ADVISORY_ONLY -- see
.agents/skills/multi-timeframe-market-context/SKILL.md for the authority contract this
package must never exceed. No import here may ever reach execution/, mt5.management_gateway,
or strategy_engine's decision path (enforced by tests/test_mtf_context_execution_guard.py).
"""
from .models import (
    ALL_ROLES,
    AUTHORITY,
    CONTEXT_READY,
    DATA_ERROR,
    INSUFFICIENT_DATA,
    INVALID_PROFILE,
    PARTIAL_CONTEXT,
    ROLE_BIAS,
    ROLE_EXECUTION,
    ROLE_MACRO,
    ROLE_MANAGEMENT,
    ROLE_SETUP,
    ROLE_WORKING,
    SKILL_ID,
    SKILL_VERSION,
    InvalidProfileError,
    LayerResult,
    MTFContext,
    MTFProfile,
)
from .orchestrator import analyze
from .topdown_contracts import (
    ALL_CANONICAL_TIMEFRAMES,
    ALLOWED_STRUCTURE_DEFINITION_IDS,
    DATA_QUALITY_DATA_ERROR,
    DATA_QUALITY_MISSING,
    DATA_QUALITY_PARTIAL,
    DATA_QUALITY_VALID,
    ALLOWED_ZONE_DEFINITION_IDS,
    ALLOWED_LIQUIDITY_DEFINITION_IDS,
    LIQUIDITY_DEFINITION_AG_LIQUIDITY_V1,
    STRUCTURE_DEFINITION_SMC_MARKET_STRUCTURE_V1,
    TIMEFRAME_D1,
    TIMEFRAME_H1,
    TIMEFRAME_H4,
    TIMEFRAME_M1,
    TIMEFRAME_M5,
    TIMEFRAME_M15,
    TIMEFRAME_W1,
    TOPDOWN_TIMEFRAMES,
    ZONE_DEFINITION_NATIVE_REFERENCE_V1,
    ZONE_DEFINITION_SMC_SUPPLY_DEMAND_V1,
    DailyContext,
    H1Context,
    H4Context,
    ImbalanceFact,
    InvalidDataQualityStatusError,
    InvalidLiquidityDefinitionError,
    InvalidStructureDefinitionError,
    InvalidTimeframeError,
    InvalidZoneDefinitionError,
    LiquidityFact,
    M5Context,
    M15Context,
    ReferenceLevelFact,
    StructureFact,
    TimeframeRequirement,
    TopDownContext,
    WeeklyContext,
    ZoneFact,
    compute_context_id,
)
from .topdown_context_adapters import (
    ADAPTER_FEATURE_VERSION,
    D1_CONTEXT_SOURCE,
    H1_CONTEXT_SOURCE,
    M5_CONTEXT_SOURCE,
    STRUCTURE_FACT_SOURCE,
    build_daily_context,
    build_h1_context,
    build_m5_context,
    daily_context_from_d1,
    h1_context_from_sources,
    m5_context_from_structure,
)
from .topdown_market_data import closed_snapshot_for_topdown_timeframe

__all__ = [
    "analyze", "MTFProfile", "MTFContext", "LayerResult", "InvalidProfileError",
    "SKILL_ID", "SKILL_VERSION", "AUTHORITY",
    "ROLE_MACRO", "ROLE_BIAS", "ROLE_WORKING", "ROLE_SETUP", "ROLE_EXECUTION", "ROLE_MANAGEMENT", "ALL_ROLES",
    "CONTEXT_READY", "PARTIAL_CONTEXT", "INSUFFICIENT_DATA", "DATA_ERROR", "INVALID_PROFILE",
    # TD-1 top-down context contracts (additive; see topdown_contracts.py)
    "TIMEFRAME_W1", "TIMEFRAME_D1", "TIMEFRAME_H4", "TIMEFRAME_H1", "TIMEFRAME_M15", "TIMEFRAME_M5", "TIMEFRAME_M1",
    "TOPDOWN_TIMEFRAMES", "ALL_CANONICAL_TIMEFRAMES",
    "DATA_QUALITY_VALID", "DATA_QUALITY_PARTIAL", "DATA_QUALITY_MISSING", "DATA_QUALITY_DATA_ERROR",
    "STRUCTURE_DEFINITION_SMC_MARKET_STRUCTURE_V1", "ALLOWED_STRUCTURE_DEFINITION_IDS",
    "InvalidTimeframeError", "InvalidDataQualityStatusError", "InvalidStructureDefinitionError",
    "StructureFact", "TimeframeRequirement", "compute_context_id",
    "WeeklyContext", "DailyContext", "H4Context", "H1Context", "M15Context", "M5Context", "TopDownContext",
    # TD-3A fact-contract amendment (additive; see topdown_contracts.py)
    "ZONE_DEFINITION_SMC_SUPPLY_DEMAND_V1", "ZONE_DEFINITION_NATIVE_REFERENCE_V1", "ALLOWED_ZONE_DEFINITION_IDS",
    "LIQUIDITY_DEFINITION_AG_LIQUIDITY_V1", "ALLOWED_LIQUIDITY_DEFINITION_IDS",
    "InvalidZoneDefinitionError", "InvalidLiquidityDefinitionError",
    "ImbalanceFact", "ZoneFact", "ReferenceLevelFact", "LiquidityFact",
    # TD-2 data foundation (additive; see topdown_market_data.py)
    "closed_snapshot_for_topdown_timeframe",
    # TD-3 existing-context adapters (additive; see topdown_context_adapters.py)
    "ADAPTER_FEATURE_VERSION", "STRUCTURE_FACT_SOURCE",
    "D1_CONTEXT_SOURCE", "H1_CONTEXT_SOURCE", "M5_CONTEXT_SOURCE",
    "daily_context_from_d1", "build_daily_context",
    "h1_context_from_sources", "build_h1_context",
    "m5_context_from_structure", "build_m5_context",
]
