"""AG_PROJECT_READINESS_AND_NEXT_GATE_RECONCILIATION_V1 -- readiness baseline generator.

Reads the canonical AG-EGSVF portfolio ledger (already generated by the validation
framework -- never recomputed here) plus a small set of already-established repository
facts (application release status, FX shadow counters, BTC campaign count, C10 sign-off
state) and writes one immutable readiness snapshot. This script performs no strategy
evaluation of its own -- it is a read-only aggregation/reference layer over evidence
that already exists.
"""
from __future__ import annotations

import datetime as dt
import json
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LEDGER_DIR = REPO_ROOT / "artifacts" / "validation_ledger"
READINESS_DIR = REPO_ROOT / "artifacts" / "readiness"


def _git_head() -> str:
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT).decode().strip()


def _latest_ledger() -> dict:
    snapshots = sorted(LEDGER_DIR.glob("AG_STRATEGY_PORTFOLIO_LEDGER_V1_*.json"), key=lambda p: p.stat().st_mtime)
    latest = snapshots[-1]
    return json.loads(latest.read_text(encoding="utf-8")), latest.name


def build_readiness_baseline() -> Path:
    ledger, ledger_name = _latest_ledger()
    head = _git_head()

    strategies_by_id = {s["strategy_id"]: s for s in ledger["strategies"]}

    baseline = {
        "framework_id": "AG_EGSVF_V1",
        "readiness_id": "AG_PROJECT_READINESS_V1",
        "evaluation_head": head,
        "source_ledger": f"artifacts/validation_ledger/{ledger_name}",
        "evaluated_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "application": {
            "release_id": "AG_TRADE_ASSISTANT_V1_0_3",
            "release_status": "RELEASE_CANDIDATE",
            "source": "config/releases/AG_TRADE_ASSISTANT_V1_0_3.yaml",
        },
        "governance_framework": {
            "foundation": "PASS",
            "cumulative_inheritance": "PASS",
            "stage_contracts": "PASS",
            "determinism_semantic_proof": "PASS",
            "determinism_artifact_provenance": "PASS",
            "evaluator_single_authority": "PASS",
            "execution_authority_separation": "PASS",
            "classification": "READY_LOCKED",
        },
        "strategies": {
            "ST_ASIAN_SWEEP_5R_V1": {
                "ledger_record": strategies_by_id.get("ST_ASIAN_SWEEP_5R_V1"),
                "historical_resolved_count": 13,
                "historical_methodology_status": "AG_OUTCOME_RESOLUTION_CONTRACT_V1_DRAFT",
                "friction_status": "NOT_INCLUDED (cost_status field on every resolved record)",
                "session_range_25_active_semantics": False,
                "session_range_25_source": "artifacts/candidate_research/model_a_session_range_25/ (candidate/research-only, non-promotional)",
                "shadow_series": {
                    "series_id": "AG_V1_0_3_FX_SHADOW_SERIES_002",
                    "valid_days": 0,
                    "invalid_days": 1,
                    "excluded_days": 0,
                    "pending_days": 0,
                    "target": 20,
                    "latest_countable_day": "2026-09-04 (Day 001, INVALID_DAY -- key-casing defect found+fixed, not counted)",
                    "latest_status": "BASELINE_VERIFIED_AWAITING_NEXT_ELIGIBLE_DAY (next eligible trading day 2026-09-07)",
                },
            },
            "ST_LIQUIDITY_SWEEP_RETEST_V1": {
                "ledger_record": strategies_by_id.get("ST_LIQUIDITY_SWEEP_RETEST_V1"),
                "campaign_count": 0,
                "campaign_target": 30,
                "campaign_source": "journal/reports/btc/ (directory absent -> 0 archived observations)",
                "provider_authority": "Bybit V5 linear perpetual, public/read-only (AG_V1_0_3_BYBIT_QUALIFICATION_EXCEPTION, APPROVED_READ_ONLY_ONLY)",
            },
            "ST_LARGE_SMC_V1": {
                "ledger_record": strategies_by_id.get("ST_LARGE_SMC_V1"),
                "c10_status": "UNSIGNED",
                "c10_owner_decision_complete": False,
                "c10_unresolved_parameters": [
                    "exact structural buffer value (owner-narrowed range: 1.0-2.0 pips, not a single value)",
                    "spread/bid-ask treatment",
                    "broker minimum-stop-distance behavior (WIDEN vs REJECT)",
                ],
                "c10_resolved_parameters": [
                    "structural anchor = each M-model's own invalidation_price (EXACT_REUSE)",
                    "direction: below anchor for LONG, above anchor for SHORT",
                    "missing anchor: fail closed",
                ],
                "c10_source": "docs/status/ST_LARGE_SMC_V1_C10_STOP_LOSS_DECISION_PACKET.md",
                "c14_status": "PARTIALLY_RESOLVED (occurrence identity + duplicate suppression resolved; live-store migration + post-fill re-entry remaining)",
            },
        },
        "execution_system": {
            "duplicate_protection": "PASS (execution/journal.py, OPEN/CLOSE share duplicate-command protection)",
            "idempotency": "PASS (atomic O_EXCL command claim, restart-safe)",
            "volume_validation": "PASS (CLOSE volume rejects non-finite/non-positive/excessive/below-minimum/above-maximum, floors to broker step)",
            "journal_protection": "PASS (deterministic hash filenames, legacy filenames still readable)",
            "replay_live_guard": "PASS (historical_replay blocks live MT5 access even if a terminal was initialized earlier)",
            "demo_capability": "DEMO_VERIFIED (2026-08-28, generic MT5 Demo round trip; not strategy-specific authorization)",
            "live_authority": "DISABLED (config/trading.yaml account.allow_live_trading: false)",
        },
        "portfolio_readiness": {
            "governance_framework": "READY_LOCKED",
            "strategy_logic": "VALIDATED_AT_DIFFERENT_MATURITY_LEVELS",
            "historical_evidence": "PARTIAL (FX 13 draft-methodology outcomes; BTC/Large-SMC none required yet at their current stage)",
            "forward_evidence": "IN_PROGRESS (FX shadow series accruing; BTC campaign not yet started; Large-SMC not yet eligible)",
            "demo_readiness": "NO (no strategy is both DEMO_ELIGIBLE and DEMO_AUTHORIZED)",
            "live_readiness": "NO (live trading disabled by default; no strategy has live_authorized=true)",
        },
        "gate_changes_since_prior_readiness_artifact": {
            "prior_artifact": "artifacts/readiness/AG_PROJECT_READINESS_V1_3f683766f22b_20260907T061909.170003+0000.json",
            "ST_LIQUIDITY_SWEEP_RETEST_V1": {
                "NO_LOOKAHEAD": "NOT_VERIFIED -> PASS (H1 future-candle-exclusion test added, AG_PROJECT_READINESS_CONTINUATION_DUAL_TRACK_V1 P3)",
            },
            "ST_LARGE_SMC_V1": {
                "C10_STOP_POLICY": "unchanged, UNSIGNED (owner decision packet V2 produced, not signed -- docs/status/AG_LARGE_SMC_V1_C10_STOP_POLICY_OWNER_DECISION_PACKET_V2_STATUS.md)",
            },
            "ST_ASIAN_SWEEP_5R_V1": "no gate change this task",
        },
        "execution_architecture": {
            "fx_demo_venue": "MT5 (VantageMarkets-Demo) -- unchanged",
            "crypto_demo_venue_target": "VT Markets Demo MT5 (owner-stated intent) -- NOT auditable in this environment; only VantageMarkets-Demo was connected/reachable",
            "shared_mt5_gateway": "execution/executor.py + execution/mt5_gateway.py -- already broker-metadata-generic (mt5/symbol_resolver.py, execution/risk.py); one narrow FX-shaped fallback noted at executor.py:299 (missing-symbol_meta case only), not fixed this task",
            "vtmarkets_crypto_audit": "ASSESSMENT_INCOMPLETE -- see docs/status/AG_VTMARKETS_CRYPTO_MT5_EXECUTION_COMPATIBILITY_E1_STATUS.md",
            "vtmarkets_crypto_symbols": "NOT AUDITED (no VT Markets terminal reachable); VantageMarkets-Demo's own BTCUSD/ETHUSD audited instead, as a secondary/labeled finding",
            "cross_venue_compatibility": "MATERIAL MISMATCH found between Bybit BTCUSDT linear perpetual (existing market-data authority) and VantageMarkets-Demo's BTCUSD CFD (different quote/margin currency, no funding mechanism, different price basis) -- requires owner-signed reconciliation before any execution routing",
            "crypto_adapter_required": "NOT DETERMINED (E2 not reached -- E1 did not confirm compatibility for the intended venue)",
            "crypto_execution_authorized": False,
            "broker_order_sent": False,
            "concurrent_unrelated_work_observed": "This task discovered unrelated, actively-changing files (config/mt5.yaml, src/execution/mt5_gateway.py, new src/mt5/{account_guard,broker_symbol_resolver,config}.py, src/.env.example, new mt5-related tests) appearing in the working tree mid-task, not created by this task and left completely untouched/uncommitted -- appears to be a concurrent, independent workstream on the same repository.",
        },
    }

    READINESS_DIR.mkdir(parents=True, exist_ok=True)
    ts = baseline["evaluated_at"].replace(":", "").replace("-", "")
    path = READINESS_DIR / f"AG_PROJECT_READINESS_V1_{head[:12]}_{ts}.json"
    suffix = 1
    while path.exists():
        path = READINESS_DIR / f"AG_PROJECT_READINESS_V1_{head[:12]}_{ts}-{suffix}.json"
        suffix += 1
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(baseline, fh, indent=2, sort_keys=True, default=str)
        fh.write("\n")
    return path


if __name__ == "__main__":
    path = build_readiness_baseline()
    print(f"wrote {path}")
