"""AG_EGSVF_V1 -- shared, read-only reader for immutable cross-strategy determinism
evidence records (artifacts/validation_evidence/determinism/), generated by
scripts/generate_determinism_evidence.py.

Every adapter's DETERMINISM gate is derived from here rather than each adapter
independently inferring a status. This module never regenerates, mutates, or deletes an
evidence record -- it only reads the most recent one that exactly matches
(strategy_id, semantic_version) and reports its own recorded `result`/
`payload_digests_equal` fields verbatim. A strategy with no matching record (wrong
version, or none ever generated) is NOT_VERIFIED, never inferred as PASS from the
record's mere existence (AG_EGSVF_V1_CROSS_STRATEGY_DETERMINISM_EVIDENCE_
RECONCILIATION, section 25: "avoid test-name-as-proof").
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, Mapping, Tuple

from validation_framework.models import GateStatus

EVIDENCE_DIR = os.path.join("artifacts", "validation_evidence", "determinism")


def load_determinism_evidence(
    repo_root: str, strategy_id: str, semantic_version: str
) -> Tuple[GateStatus, Tuple[str, ...], Mapping[str, Any]]:
    """Returns (status, evidence_refs, details) for a strategy's DETERMINISM gate.

    status is PASS only if a matching record exists AND records result == "PASS" AND
    payload_digests_equal is True. It is FAIL if a matching record exists but recorded a
    genuine digest mismatch (a real nondeterminism defect, never softened to PARTIAL --
    section 33). It is NOT_VERIFIED if no record exists for this exact
    (strategy_id, semantic_version) -- including when only a record for a *different*
    version exists, per the version-bound-evidence invariant.
    """
    directory = os.path.join(repo_root, EVIDENCE_DIR)
    if not os.path.isdir(directory):
        return (
            GateStatus.NOT_VERIFIED,
            (),
            {"note": "no artifacts/validation_evidence/determinism/ directory found"},
        )

    prefix = f"{strategy_id}_{semantic_version}_"
    matches = []
    for name in sorted(os.listdir(directory)):
        if not name.startswith(prefix) or not name.endswith(".json"):
            continue
        path = os.path.join(directory, name)
        with open(path, "r", encoding="utf-8") as fh:
            record = json.load(fh)
        # Defensive re-check: filename convention alone is never trusted as identity.
        if record.get("strategy_id") != strategy_id or record.get("strategy_version") != semantic_version:
            continue
        matches.append((name, record))

    if not matches:
        return (
            GateStatus.NOT_VERIFIED,
            (),
            {"note": f"no determinism evidence record found for ({strategy_id}, {semantic_version})"},
        )

    name, record = max(matches, key=lambda item: item[1].get("evaluated_at", ""))
    ref = os.path.join(EVIDENCE_DIR, name).replace("\\", "/")

    if record.get("result") == "PASS" and record.get("payload_digests_equal") is True:
        status = GateStatus.PASS
    else:
        status = GateStatus.FAIL

    details: Dict[str, Any] = {
        "runs": record.get("runs"),
        "evaluation_head": record.get("evaluation_head"),
        "test_ref": record.get("test_ref"),
        "fixture_ref": record.get("fixture_ref"),
        "payload_digests_equal": record.get("payload_digests_equal"),
        "evaluated_at": record.get("evaluated_at"),
    }
    return status, (ref,), details
